# Generated by Django 3.1.1 on 2020-09-15 18:31

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GCCache',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, null=True)),
                ('expire_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='URLBlacklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='URLRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_url', models.CharField(max_length=300)),
                ('url_filter', models.CharField(max_length=300)),
                ('language', models.CharField(choices=[('el', 'el'), ('en', 'en'), ('ru', 'ru')], default='el', max_length=2)),
                ('active', models.BooleanField(default=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='journalist.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=300, unique=True)),
                ('original_language', models.CharField(choices=[('el', 'el'), ('en', 'en'), ('ru', 'ru')], default='el', max_length=2)),
                ('original_title', models.CharField(max_length=300, unique=True)),
                ('original_text', models.TextField()),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('summary', tinymce.models.HTMLField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NW', 'New'), ('RD', 'Ready')], db_index=True, default='NW', max_length=2)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='journalist.topic')),
                ('url_recommendations', models.ManyToManyField(blank=True, to='journalist.URLRecommendation')),
            ],
        ),
    ]
